version: '3.8'
services:
  db:
    build: ./db
    container_name: devops_db
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
    restart: always

  app:
    build: .
    container_name: devops_app
    depends_on:
      - db
    environment:
      - JDBC_URL=jdbc:mysql://db:3306/employees?allowPublicKeyRetrieval=true&useSSL=false
      - DB_USER=root
      - DB_PASS=example
    tty: true
